adds readme with wireframes
INF6420/ss22-hp1046 pull request #2
Opened 2023-05-13 17:55 UTC by hp1046

2023-05-15 12:47 UTC, axamei requested changes

2023-05-15 12:47 UTC, axamei commented on README.md
> +![Wireframe of Home Page](wireframes\home.jpg)
You want to use `/` instead of `\`

2023-05-15 12:47 UTC, axamei commented on README.md
> +![Wireframe of Education and Certification](wireframes\education-and-certification.jpg)
You want to use `/` instead of `\`

2023-05-15 12:47 UTC, axamei commented on README.md
> +![Wireframe of Home Page](wireframes\work-experience-and-professional-development.jpg)
You want to use `/` instead of `\`

2023-05-15 20:36 UTC, hp1046 commented on README.md
> +![Wireframe of Home Page](wireframes\home.jpg)
@axamei Fixed! Thank you!

2023-05-15 20:36 UTC, hp1046 commented on README.md
> +![Wireframe of Education and Certification](wireframes\education-and-certification.jpg)
@axamei Fixed! Thank you!

2023-05-15 20:36 UTC, hp1046 commented on README.md
> +![Wireframe of Home Page](wireframes\work-experience-and-professional-development.jpg)
@axamei Fixed! Thank you!

2023-05-16 13:14 UTC, axamei approved these changes

2023-05-16 13:14 UTC, merged